### ISSUE TITLE
Enhance documentation

### ISSUE THREAD

**Issue by kaushalkumar99** [SukhmeetSingh2002/Cli-Chat#8]
**Is your feature request related to a problem? Please describe.**
The documentation can be more precise and descriptive
**Describe the solution you'd like**
I would like to make the documentation more interesting and eye catchy which will attract more users
**Describe alternatives you've considered**
Adding gifs process snaps,etc
**Additional context**
You can check my previous contribution to documentation which  is merged to a repo and is using it amazingly

**Comment by Ratikant-rout** [comment]
Hello @kaushalkumar99 Can You Please Assign me This Issue?
